# Generated by Django 4.2.3 on 2023-07-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='Pizza name')),
                ('content', models.TextField(blank=True, max_length=70, verbose_name='Description')),
                ('weight', models.IntegerField(blank=True, verbose_name='Weight')),
                ('price', models.IntegerField(blank=True, verbose_name='Price')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
            ],
        ),
    ]
