# Generated by Django 4.2.3 on 2023-07-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Pizza name'),
        ),
    ]
