# Generated by Django 4.2.3 on 2023-07-24 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart_cartitem_cart_items_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', through='main.CartItem', to='main.pizza'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='main.pizza'),
        ),
    ]
