# Generated by Django 4.2.3 on 2023-07-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cart_items_alter_cartitem_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='stripe',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Stripe ID'),
        ),
    ]
